import React from 'react';
import { 
  Shield, Lock, AlertTriangle, Eye, HelpCircle, 
  ExternalLink, FileCheck, CheckCircle2, UserX, AlertOctagon
} from 'lucide-react';

export const PrivacyAndAbout: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-8">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-white flex items-center space-x-2">
          <Shield className="w-6 h-6 text-blue-400" />
          <span>Ethics, Privacy & Operational Limitations</span>
        </h2>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          ScamShield AI architecture principles, data protection commitments, and responsible disclosure standards.
        </p>
      </div>

      {/* 1. Scientific & Legal Limitations */}
      <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-3">
        <h3 className="text-base font-bold text-white flex items-center space-x-2">
          <AlertOctagon className="w-5 h-5 text-amber-400" />
          <span>Risk Score Limitations & Legal Disclaimer</span>
        </h3>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          The risk scores (0 to 100) generated by ScamShield AI are <strong>probabilistic estimates</strong> derived from statistical machine learning algorithms and heuristic pattern matching.
        </p>
        <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-300 space-y-2">
          <div className="flex items-start space-x-2">
            <span className="text-amber-400 font-bold">•</span>
            <span><strong>Not Legal Proof:</strong> A high risk score does not constitute legal proof or formal accusation that an individual or organization has committed criminal fraud.</span>
          </div>
          <div className="flex items-start space-x-2">
            <span className="text-amber-400 font-bold">•</span>
            <span><strong>False Positives / Negatives:</strong> Emerging scam tactics may evade pattern detection (false negative), and legitimate recruiters using unconventional templates may trigger warnings (false positive).</span>
          </div>
          <div className="flex items-start space-x-2">
            <span className="text-amber-400 font-bold">•</span>
            <span><strong>Independent Verification:</strong> Users must always verify company credentials through independent telephone switchboards, verified LinkedIn rosters, and official DNS MX records.</span>
          </div>
        </div>
      </div>

      {/* 2. Privacy & Zero Credential Collection */}
      <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-4">
        <h3 className="text-base font-bold text-white flex items-center space-x-2">
          <Lock className="w-5 h-5 text-emerald-400" />
          <span>Privacy Architecture & Zero Credential Collection</span>
        </h3>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          ScamShield AI is engineered around strict data minimization and anti-credential-harvesting principles:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
            <div className="font-semibold text-white mb-1 flex items-center space-x-1.5">
              <UserX className="w-4 h-4 text-emerald-400" />
              <span>Zero Credential Requests</span>
            </div>
            <p className="text-slate-400 leading-relaxed">
              We will never ask for your passwords, one-time passcodes (OTPs), bank PINs, Social Security Numbers, or credit card numbers. If any prompt requests these, cease interaction immediately.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
            <div className="font-semibold text-white mb-1 flex items-center space-x-1.5">
              <Eye className="w-4 h-4 text-blue-400" />
              <span>Auditable Local & Server History</span>
            </div>
            <p className="text-slate-400 leading-relaxed">
              Analyses are stored solely within your configured application session. You can search, inspect, or permanently delete your audit trail with one click at any time.
            </p>
          </div>
        </div>
      </div>

      {/* 3. Official Scam Reporting Authorities */}
      <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-4">
        <h3 className="text-base font-bold text-white flex items-center space-x-2">
          <ExternalLink className="w-5 h-5 text-blue-400" />
          <span>Where to Report Active Job Scams</span>
        </h3>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          If you have encountered or been targeted by an employment fraud campaign, report it directly to these law enforcement and consumer protection bureaus:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <a
            href="https://reportfraud.ftc.gov"
            target="_blank"
            rel="noopener noreferrer"
            className="p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-blue-500/50 transition-colors block"
          >
            <div className="font-bold text-white mb-1">FTC Report Fraud</div>
            <div className="text-slate-400">reportfraud.ftc.gov</div>
            <div className="text-[11px] text-blue-400 mt-2">United States Federal Trade Commission →</div>
          </a>

          <a
            href="https://www.ic3.gov"
            target="_blank"
            rel="noopener noreferrer"
            className="p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-blue-500/50 transition-colors block"
          >
            <div className="font-bold text-white mb-1">FBI IC3</div>
            <div className="text-slate-400">ic3.gov</div>
            <div className="text-[11px] text-blue-400 mt-2">Internet Crime Complaint Center →</div>
          </a>

          <a
            href="https://www.bbb.org/scamtracker"
            target="_blank"
            rel="noopener noreferrer"
            className="p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-blue-500/50 transition-colors block"
          >
            <div className="font-bold text-white mb-1">BBB Scam Tracker</div>
            <div className="text-slate-400">bbb.org/scamtracker</div>
            <div className="text-[11px] text-blue-400 mt-2">Better Business Bureau Directory →</div>
          </a>
        </div>
      </div>
    </div>
  );
};
